box_descriptions:
  type: list
  default: "2; Welcome and get started here.|5; Share your #madewithvectornator art.|6; Stay up-to-date on whatâ€™s going on at Vectornator.|7; Share your Vectornator hints with the community.|8; Let us know your product feedback and requests.|9; Tell us about yourself and connect with others.|10; Ask product questions, get help, and give support.|11; Came across a bug? Let us know."
  description:
    en: 'Semicolon delimited in this order: Category Id;Description<br><b>Category Id:</b> The unique category number when navigating to the category. E.g. 5 in "/c/gallery/5"<br><b>Description:</b> A short description. Will only be shown on category boxes on the landing page'
